- name: Learning command modules and storing output
  hosts: all
  become: yes
  tasks:
    - name: example copying file with owner and permissions
      template:
       src: templates/motd.j2
       dest: /etc/motd
   
    - name: return motd to registered var
      command: cat /etc/motd
      register: mymotd

    - debug:
       msg: "The banner is {{mymotd.stdout}}"
